source 'https://git.hzdlsoft.com/ios_lib/DLPods.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :ios, '9.0'



target 'TestDemo' do
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
  'RCTText',
  'RCTNetwork',
  'BatchedBridge',
  'RCTWebSocket', # 这个模块是用于调试功能的
  # 在这里继续添加你所需要的模块
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'DLShareModuleIOS', :path => '../node_modules/@ecool/react-native-dlsharemodule'

end

